version: '3'

tasks:
  tf-validate:
    desc: Validate terraform
    aliases: [validate]
    deps: [fmt]
    cmds:
      - terraform validate

  tf-apply:
    desc: Apply terraform
    aliases: [apply]
    deps: [validate]
    vars:
      ENV: dev
    cmds:
      - for: ['vpc', 'ecs-cluster']
        cmd: cd {{ .ITEM }} && terraform apply -auto-approve -var-file=environment/{{.ENV}}/terraform.tfvars

  tf-format:
    desc: Format all terraform files
    aliases: [fmt]
    cmds:
      - for: ['vpc', 'ecs-cluster']
        cmd: cd {{ .ITEM }} && terraform fmt --recursive

  tf-destroy:
    desc: Destroy all services created by terraform
    aliases: [destroy]
    deps: [validate]
    vars:
      ENV: dev
    cmds:
      - for: ['ecs-cluster', 'vpc']
        cmd: cd {{ .ITEM }} && terraform destroy -auto-approve -var-file=environment/{{.ENV}}/terraform.tfvars