version: '3'

tasks:
  tf-apply:
    desc: Apply terraform
    aliases: [apply]
    vars:
      ENV: dev
    cmds:
      - terraform apply -auto-approve -var-file=environment/{{.ENV}}/terraform.tfvars

  tf-format:
    desc: Format all terraform files
    aliases: [fmt]
    cmds:
      - terraform fmt --recursive

  tf-destroy:
    desc: Destroy all services created by terraform
    aliases: [destroy]
    vars:
      ENV: dev
    cmds:
      - terraform destroy -auto-approve -var-file=environment/{{.ENV}}/terraform.tfvars